# CMAKE generated file: DO NOT EDIT!
# Generated by "Unix Makefiles" Generator, CMake Version 3.14

# Default target executed when no arguments are given to make.
default_target: all

.PHONY : default_target

# Allow only one "make -f Makefile2" at a time, but pass parallelism.
.NOTPARALLEL:


#=============================================================================
# Special targets provided by cmake.

# Disable implicit rules so canonical targets will work.
.SUFFIXES:


# Remove some rules from gmake that .SUFFIXES does not remove.
SUFFIXES =

.SUFFIXES: .hpux_make_needs_suffix_list


# Suppress display of executed commands.
$(VERBOSE).SILENT:


# A target that is always out of date.
cmake_force:

.PHONY : cmake_force

#=============================================================================
# Set environment variables for the build.

# The shell in which to execute make rules.
SHELL = /bin/sh

# The CMake executable.
CMAKE_COMMAND = /usr/local/bin/cmake

# The command to remove a file.
RM = /usr/local/bin/cmake -E remove -f

# Escaping for special characters.
EQUALS = =

# The top-level source directory on which CMake was run.
CMAKE_SOURCE_DIR = /home/kaihuo/cvm-runtime

# The top-level build directory on which CMake was run.
CMAKE_BINARY_DIR = /home/kaihuo/cvm-runtime

#=============================================================================
# Targets provided globally by CMake.

# Special rule for the target install/strip
install/strip: preinstall
	@$(CMAKE_COMMAND) -E cmake_echo_color --switch=$(COLOR) --cyan "Installing the project stripped..."
	/usr/local/bin/cmake -DCMAKE_INSTALL_DO_STRIP=1 -P cmake_install.cmake
.PHONY : install/strip

# Special rule for the target install/strip
install/strip/fast: preinstall/fast
	@$(CMAKE_COMMAND) -E cmake_echo_color --switch=$(COLOR) --cyan "Installing the project stripped..."
	/usr/local/bin/cmake -DCMAKE_INSTALL_DO_STRIP=1 -P cmake_install.cmake
.PHONY : install/strip/fast

# Special rule for the target install/local
install/local: preinstall
	@$(CMAKE_COMMAND) -E cmake_echo_color --switch=$(COLOR) --cyan "Installing only the local directory..."
	/usr/local/bin/cmake -DCMAKE_INSTALL_LOCAL_ONLY=1 -P cmake_install.cmake
.PHONY : install/local

# Special rule for the target install/local
install/local/fast: preinstall/fast
	@$(CMAKE_COMMAND) -E cmake_echo_color --switch=$(COLOR) --cyan "Installing only the local directory..."
	/usr/local/bin/cmake -DCMAKE_INSTALL_LOCAL_ONLY=1 -P cmake_install.cmake
.PHONY : install/local/fast

# Special rule for the target install
install: preinstall
	@$(CMAKE_COMMAND) -E cmake_echo_color --switch=$(COLOR) --cyan "Install the project..."
	/usr/local/bin/cmake -P cmake_install.cmake
.PHONY : install

# Special rule for the target install
install/fast: preinstall/fast
	@$(CMAKE_COMMAND) -E cmake_echo_color --switch=$(COLOR) --cyan "Install the project..."
	/usr/local/bin/cmake -P cmake_install.cmake
.PHONY : install/fast

# Special rule for the target list_install_components
list_install_components:
	@$(CMAKE_COMMAND) -E cmake_echo_color --switch=$(COLOR) --cyan "Available install components are: \"Unspecified\""
.PHONY : list_install_components

# Special rule for the target list_install_components
list_install_components/fast: list_install_components

.PHONY : list_install_components/fast

# Special rule for the target rebuild_cache
rebuild_cache:
	@$(CMAKE_COMMAND) -E cmake_echo_color --switch=$(COLOR) --cyan "Running CMake to regenerate build system..."
	/usr/local/bin/cmake -S$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR)
.PHONY : rebuild_cache

# Special rule for the target rebuild_cache
rebuild_cache/fast: rebuild_cache

.PHONY : rebuild_cache/fast

# Special rule for the target edit_cache
edit_cache:
	@$(CMAKE_COMMAND) -E cmake_echo_color --switch=$(COLOR) --cyan "Running CMake cache editor..."
	/usr/local/bin/ccmake -S$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR)
.PHONY : edit_cache

# Special rule for the target edit_cache
edit_cache/fast: edit_cache

.PHONY : edit_cache/fast

# The main all target
all: cmake_check_build_system
	$(CMAKE_COMMAND) -E cmake_progress_start /home/kaihuo/cvm-runtime/CMakeFiles /home/kaihuo/cvm-runtime/CMakeFiles/progress.marks
	$(MAKE) -f CMakeFiles/Makefile2 all
	$(CMAKE_COMMAND) -E cmake_progress_start /home/kaihuo/cvm-runtime/CMakeFiles 0
.PHONY : all

# The main clean target
clean:
	$(MAKE) -f CMakeFiles/Makefile2 clean
.PHONY : clean

# The main clean target
clean/fast: clean

.PHONY : clean/fast

# Prepare targets for installation.
preinstall: all
	$(MAKE) -f CMakeFiles/Makefile2 preinstall
.PHONY : preinstall

# Prepare targets for installation.
preinstall/fast:
	$(MAKE) -f CMakeFiles/Makefile2 preinstall
.PHONY : preinstall/fast

# clear depends
depend:
	$(CMAKE_COMMAND) -S$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR) --check-build-system CMakeFiles/Makefile.cmake 1
.PHONY : depend

#=============================================================================
# Target rules for targets named cvm_runtime

# Build rule for target.
cvm_runtime: cmake_check_build_system
	$(MAKE) -f CMakeFiles/Makefile2 cvm_runtime
.PHONY : cvm_runtime

# fast build rule for target.
cvm_runtime/fast:
	$(MAKE) -f CMakeFiles/cvm_runtime.dir/build.make CMakeFiles/cvm_runtime.dir/build
.PHONY : cvm_runtime/fast

#=============================================================================
# Target rules for targets named runtime

# Build rule for target.
runtime: cmake_check_build_system
	$(MAKE) -f CMakeFiles/Makefile2 runtime
.PHONY : runtime

# fast build rule for target.
runtime/fast:
	$(MAKE) -f CMakeFiles/runtime.dir/build.make CMakeFiles/runtime.dir/build
.PHONY : runtime/fast

src/runtime/c_dsl_api.o: src/runtime/c_dsl_api.cc.o

.PHONY : src/runtime/c_dsl_api.o

# target to build an object file
src/runtime/c_dsl_api.cc.o:
	$(MAKE) -f CMakeFiles/cvm_runtime.dir/build.make CMakeFiles/cvm_runtime.dir/src/runtime/c_dsl_api.cc.o
.PHONY : src/runtime/c_dsl_api.cc.o

src/runtime/c_dsl_api.i: src/runtime/c_dsl_api.cc.i

.PHONY : src/runtime/c_dsl_api.i

# target to preprocess a source file
src/runtime/c_dsl_api.cc.i:
	$(MAKE) -f CMakeFiles/cvm_runtime.dir/build.make CMakeFiles/cvm_runtime.dir/src/runtime/c_dsl_api.cc.i
.PHONY : src/runtime/c_dsl_api.cc.i

src/runtime/c_dsl_api.s: src/runtime/c_dsl_api.cc.s

.PHONY : src/runtime/c_dsl_api.s

# target to generate assembly for a file
src/runtime/c_dsl_api.cc.s:
	$(MAKE) -f CMakeFiles/cvm_runtime.dir/build.make CMakeFiles/cvm_runtime.dir/src/runtime/c_dsl_api.cc.s
.PHONY : src/runtime/c_dsl_api.cc.s

src/runtime/c_runtime_api.o: src/runtime/c_runtime_api.cc.o

.PHONY : src/runtime/c_runtime_api.o

# target to build an object file
src/runtime/c_runtime_api.cc.o:
	$(MAKE) -f CMakeFiles/cvm_runtime.dir/build.make CMakeFiles/cvm_runtime.dir/src/runtime/c_runtime_api.cc.o
.PHONY : src/runtime/c_runtime_api.cc.o

src/runtime/c_runtime_api.i: src/runtime/c_runtime_api.cc.i

.PHONY : src/runtime/c_runtime_api.i

# target to preprocess a source file
src/runtime/c_runtime_api.cc.i:
	$(MAKE) -f CMakeFiles/cvm_runtime.dir/build.make CMakeFiles/cvm_runtime.dir/src/runtime/c_runtime_api.cc.i
.PHONY : src/runtime/c_runtime_api.cc.i

src/runtime/c_runtime_api.s: src/runtime/c_runtime_api.cc.s

.PHONY : src/runtime/c_runtime_api.s

# target to generate assembly for a file
src/runtime/c_runtime_api.cc.s:
	$(MAKE) -f CMakeFiles/cvm_runtime.dir/build.make CMakeFiles/cvm_runtime.dir/src/runtime/c_runtime_api.cc.s
.PHONY : src/runtime/c_runtime_api.cc.s

src/runtime/cpu_device_api.o: src/runtime/cpu_device_api.cc.o

.PHONY : src/runtime/cpu_device_api.o

# target to build an object file
src/runtime/cpu_device_api.cc.o:
	$(MAKE) -f CMakeFiles/cvm_runtime.dir/build.make CMakeFiles/cvm_runtime.dir/src/runtime/cpu_device_api.cc.o
.PHONY : src/runtime/cpu_device_api.cc.o

src/runtime/cpu_device_api.i: src/runtime/cpu_device_api.cc.i

.PHONY : src/runtime/cpu_device_api.i

# target to preprocess a source file
src/runtime/cpu_device_api.cc.i:
	$(MAKE) -f CMakeFiles/cvm_runtime.dir/build.make CMakeFiles/cvm_runtime.dir/src/runtime/cpu_device_api.cc.i
.PHONY : src/runtime/cpu_device_api.cc.i

src/runtime/cpu_device_api.s: src/runtime/cpu_device_api.cc.s

.PHONY : src/runtime/cpu_device_api.s

# target to generate assembly for a file
src/runtime/cpu_device_api.cc.s:
	$(MAKE) -f CMakeFiles/cvm_runtime.dir/build.make CMakeFiles/cvm_runtime.dir/src/runtime/cpu_device_api.cc.s
.PHONY : src/runtime/cpu_device_api.cc.s

src/runtime/cuda/cuda_device_api.o: src/runtime/cuda/cuda_device_api.cc.o

.PHONY : src/runtime/cuda/cuda_device_api.o

# target to build an object file
src/runtime/cuda/cuda_device_api.cc.o:
	$(MAKE) -f CMakeFiles/cvm_runtime.dir/build.make CMakeFiles/cvm_runtime.dir/src/runtime/cuda/cuda_device_api.cc.o
.PHONY : src/runtime/cuda/cuda_device_api.cc.o

src/runtime/cuda/cuda_device_api.i: src/runtime/cuda/cuda_device_api.cc.i

.PHONY : src/runtime/cuda/cuda_device_api.i

# target to preprocess a source file
src/runtime/cuda/cuda_device_api.cc.i:
	$(MAKE) -f CMakeFiles/cvm_runtime.dir/build.make CMakeFiles/cvm_runtime.dir/src/runtime/cuda/cuda_device_api.cc.i
.PHONY : src/runtime/cuda/cuda_device_api.cc.i

src/runtime/cuda/cuda_device_api.s: src/runtime/cuda/cuda_device_api.cc.s

.PHONY : src/runtime/cuda/cuda_device_api.s

# target to generate assembly for a file
src/runtime/cuda/cuda_device_api.cc.s:
	$(MAKE) -f CMakeFiles/cvm_runtime.dir/build.make CMakeFiles/cvm_runtime.dir/src/runtime/cuda/cuda_device_api.cc.s
.PHONY : src/runtime/cuda/cuda_device_api.cc.s

src/runtime/cuda/cuda_module.o: src/runtime/cuda/cuda_module.cc.o

.PHONY : src/runtime/cuda/cuda_module.o

# target to build an object file
src/runtime/cuda/cuda_module.cc.o:
	$(MAKE) -f CMakeFiles/cvm_runtime.dir/build.make CMakeFiles/cvm_runtime.dir/src/runtime/cuda/cuda_module.cc.o
.PHONY : src/runtime/cuda/cuda_module.cc.o

src/runtime/cuda/cuda_module.i: src/runtime/cuda/cuda_module.cc.i

.PHONY : src/runtime/cuda/cuda_module.i

# target to preprocess a source file
src/runtime/cuda/cuda_module.cc.i:
	$(MAKE) -f CMakeFiles/cvm_runtime.dir/build.make CMakeFiles/cvm_runtime.dir/src/runtime/cuda/cuda_module.cc.i
.PHONY : src/runtime/cuda/cuda_module.cc.i

src/runtime/cuda/cuda_module.s: src/runtime/cuda/cuda_module.cc.s

.PHONY : src/runtime/cuda/cuda_module.s

# target to generate assembly for a file
src/runtime/cuda/cuda_module.cc.s:
	$(MAKE) -f CMakeFiles/cvm_runtime.dir/build.make CMakeFiles/cvm_runtime.dir/src/runtime/cuda/cuda_module.cc.s
.PHONY : src/runtime/cuda/cuda_module.cc.s

src/runtime/cvm/graph_runtime.o: src/runtime/cvm/graph_runtime.cc.o

.PHONY : src/runtime/cvm/graph_runtime.o

# target to build an object file
src/runtime/cvm/graph_runtime.cc.o:
	$(MAKE) -f CMakeFiles/cvm_runtime.dir/build.make CMakeFiles/cvm_runtime.dir/src/runtime/cvm/graph_runtime.cc.o
.PHONY : src/runtime/cvm/graph_runtime.cc.o

src/runtime/cvm/graph_runtime.i: src/runtime/cvm/graph_runtime.cc.i

.PHONY : src/runtime/cvm/graph_runtime.i

# target to preprocess a source file
src/runtime/cvm/graph_runtime.cc.i:
	$(MAKE) -f CMakeFiles/cvm_runtime.dir/build.make CMakeFiles/cvm_runtime.dir/src/runtime/cvm/graph_runtime.cc.i
.PHONY : src/runtime/cvm/graph_runtime.cc.i

src/runtime/cvm/graph_runtime.s: src/runtime/cvm/graph_runtime.cc.s

.PHONY : src/runtime/cvm/graph_runtime.s

# target to generate assembly for a file
src/runtime/cvm/graph_runtime.cc.s:
	$(MAKE) -f CMakeFiles/cvm_runtime.dir/build.make CMakeFiles/cvm_runtime.dir/src/runtime/cvm/graph_runtime.cc.s
.PHONY : src/runtime/cvm/graph_runtime.cc.s

src/runtime/cvm/infer_attr.o: src/runtime/cvm/infer_attr.cc.o

.PHONY : src/runtime/cvm/infer_attr.o

# target to build an object file
src/runtime/cvm/infer_attr.cc.o:
	$(MAKE) -f CMakeFiles/cvm_runtime.dir/build.make CMakeFiles/cvm_runtime.dir/src/runtime/cvm/infer_attr.cc.o
.PHONY : src/runtime/cvm/infer_attr.cc.o

src/runtime/cvm/infer_attr.i: src/runtime/cvm/infer_attr.cc.i

.PHONY : src/runtime/cvm/infer_attr.i

# target to preprocess a source file
src/runtime/cvm/infer_attr.cc.i:
	$(MAKE) -f CMakeFiles/cvm_runtime.dir/build.make CMakeFiles/cvm_runtime.dir/src/runtime/cvm/infer_attr.cc.i
.PHONY : src/runtime/cvm/infer_attr.cc.i

src/runtime/cvm/infer_attr.s: src/runtime/cvm/infer_attr.cc.s

.PHONY : src/runtime/cvm/infer_attr.s

# target to generate assembly for a file
src/runtime/cvm/infer_attr.cc.s:
	$(MAKE) -f CMakeFiles/cvm_runtime.dir/build.make CMakeFiles/cvm_runtime.dir/src/runtime/cvm/infer_attr.cc.s
.PHONY : src/runtime/cvm/infer_attr.cc.s

src/runtime/cvm/ops.o: src/runtime/cvm/ops.cc.o

.PHONY : src/runtime/cvm/ops.o

# target to build an object file
src/runtime/cvm/ops.cc.o:
	$(MAKE) -f CMakeFiles/cvm_runtime.dir/build.make CMakeFiles/cvm_runtime.dir/src/runtime/cvm/ops.cc.o
.PHONY : src/runtime/cvm/ops.cc.o

src/runtime/cvm/ops.i: src/runtime/cvm/ops.cc.i

.PHONY : src/runtime/cvm/ops.i

# target to preprocess a source file
src/runtime/cvm/ops.cc.i:
	$(MAKE) -f CMakeFiles/cvm_runtime.dir/build.make CMakeFiles/cvm_runtime.dir/src/runtime/cvm/ops.cc.i
.PHONY : src/runtime/cvm/ops.cc.i

src/runtime/cvm/ops.s: src/runtime/cvm/ops.cc.s

.PHONY : src/runtime/cvm/ops.s

# target to generate assembly for a file
src/runtime/cvm/ops.cc.s:
	$(MAKE) -f CMakeFiles/cvm_runtime.dir/build.make CMakeFiles/cvm_runtime.dir/src/runtime/cvm/ops.cc.s
.PHONY : src/runtime/cvm/ops.cc.s

src/runtime/cvm/top/nn/convolution.o: src/runtime/cvm/top/nn/convolution.cc.o

.PHONY : src/runtime/cvm/top/nn/convolution.o

# target to build an object file
src/runtime/cvm/top/nn/convolution.cc.o:
	$(MAKE) -f CMakeFiles/cvm_runtime.dir/build.make CMakeFiles/cvm_runtime.dir/src/runtime/cvm/top/nn/convolution.cc.o
.PHONY : src/runtime/cvm/top/nn/convolution.cc.o

src/runtime/cvm/top/nn/convolution.i: src/runtime/cvm/top/nn/convolution.cc.i

.PHONY : src/runtime/cvm/top/nn/convolution.i

# target to preprocess a source file
src/runtime/cvm/top/nn/convolution.cc.i:
	$(MAKE) -f CMakeFiles/cvm_runtime.dir/build.make CMakeFiles/cvm_runtime.dir/src/runtime/cvm/top/nn/convolution.cc.i
.PHONY : src/runtime/cvm/top/nn/convolution.cc.i

src/runtime/cvm/top/nn/convolution.s: src/runtime/cvm/top/nn/convolution.cc.s

.PHONY : src/runtime/cvm/top/nn/convolution.s

# target to generate assembly for a file
src/runtime/cvm/top/nn/convolution.cc.s:
	$(MAKE) -f CMakeFiles/cvm_runtime.dir/build.make CMakeFiles/cvm_runtime.dir/src/runtime/cvm/top/nn/convolution.cc.s
.PHONY : src/runtime/cvm/top/nn/convolution.cc.s

src/runtime/cvm/top/nn/nn.o: src/runtime/cvm/top/nn/nn.cc.o

.PHONY : src/runtime/cvm/top/nn/nn.o

# target to build an object file
src/runtime/cvm/top/nn/nn.cc.o:
	$(MAKE) -f CMakeFiles/cvm_runtime.dir/build.make CMakeFiles/cvm_runtime.dir/src/runtime/cvm/top/nn/nn.cc.o
.PHONY : src/runtime/cvm/top/nn/nn.cc.o

src/runtime/cvm/top/nn/nn.i: src/runtime/cvm/top/nn/nn.cc.i

.PHONY : src/runtime/cvm/top/nn/nn.i

# target to preprocess a source file
src/runtime/cvm/top/nn/nn.cc.i:
	$(MAKE) -f CMakeFiles/cvm_runtime.dir/build.make CMakeFiles/cvm_runtime.dir/src/runtime/cvm/top/nn/nn.cc.i
.PHONY : src/runtime/cvm/top/nn/nn.cc.i

src/runtime/cvm/top/nn/nn.s: src/runtime/cvm/top/nn/nn.cc.s

.PHONY : src/runtime/cvm/top/nn/nn.s

# target to generate assembly for a file
src/runtime/cvm/top/nn/nn.cc.s:
	$(MAKE) -f CMakeFiles/cvm_runtime.dir/build.make CMakeFiles/cvm_runtime.dir/src/runtime/cvm/top/nn/nn.cc.s
.PHONY : src/runtime/cvm/top/nn/nn.cc.s

src/runtime/cvm/top/nn/pooling.o: src/runtime/cvm/top/nn/pooling.cc.o

.PHONY : src/runtime/cvm/top/nn/pooling.o

# target to build an object file
src/runtime/cvm/top/nn/pooling.cc.o:
	$(MAKE) -f CMakeFiles/cvm_runtime.dir/build.make CMakeFiles/cvm_runtime.dir/src/runtime/cvm/top/nn/pooling.cc.o
.PHONY : src/runtime/cvm/top/nn/pooling.cc.o

src/runtime/cvm/top/nn/pooling.i: src/runtime/cvm/top/nn/pooling.cc.i

.PHONY : src/runtime/cvm/top/nn/pooling.i

# target to preprocess a source file
src/runtime/cvm/top/nn/pooling.cc.i:
	$(MAKE) -f CMakeFiles/cvm_runtime.dir/build.make CMakeFiles/cvm_runtime.dir/src/runtime/cvm/top/nn/pooling.cc.i
.PHONY : src/runtime/cvm/top/nn/pooling.cc.i

src/runtime/cvm/top/nn/pooling.s: src/runtime/cvm/top/nn/pooling.cc.s

.PHONY : src/runtime/cvm/top/nn/pooling.s

# target to generate assembly for a file
src/runtime/cvm/top/nn/pooling.cc.s:
	$(MAKE) -f CMakeFiles/cvm_runtime.dir/build.make CMakeFiles/cvm_runtime.dir/src/runtime/cvm/top/nn/pooling.cc.s
.PHONY : src/runtime/cvm/top/nn/pooling.cc.s

src/runtime/cvm/top/node.o: src/runtime/cvm/top/node.cc.o

.PHONY : src/runtime/cvm/top/node.o

# target to build an object file
src/runtime/cvm/top/node.cc.o:
	$(MAKE) -f CMakeFiles/cvm_runtime.dir/build.make CMakeFiles/cvm_runtime.dir/src/runtime/cvm/top/node.cc.o
.PHONY : src/runtime/cvm/top/node.cc.o

src/runtime/cvm/top/node.i: src/runtime/cvm/top/node.cc.i

.PHONY : src/runtime/cvm/top/node.i

# target to preprocess a source file
src/runtime/cvm/top/node.cc.i:
	$(MAKE) -f CMakeFiles/cvm_runtime.dir/build.make CMakeFiles/cvm_runtime.dir/src/runtime/cvm/top/node.cc.i
.PHONY : src/runtime/cvm/top/node.cc.i

src/runtime/cvm/top/node.s: src/runtime/cvm/top/node.cc.s

.PHONY : src/runtime/cvm/top/node.s

# target to generate assembly for a file
src/runtime/cvm/top/node.cc.s:
	$(MAKE) -f CMakeFiles/cvm_runtime.dir/build.make CMakeFiles/cvm_runtime.dir/src/runtime/cvm/top/node.cc.s
.PHONY : src/runtime/cvm/top/node.cc.s

src/runtime/cvm/top/op.o: src/runtime/cvm/top/op.cc.o

.PHONY : src/runtime/cvm/top/op.o

# target to build an object file
src/runtime/cvm/top/op.cc.o:
	$(MAKE) -f CMakeFiles/cvm_runtime.dir/build.make CMakeFiles/cvm_runtime.dir/src/runtime/cvm/top/op.cc.o
.PHONY : src/runtime/cvm/top/op.cc.o

src/runtime/cvm/top/op.i: src/runtime/cvm/top/op.cc.i

.PHONY : src/runtime/cvm/top/op.i

# target to preprocess a source file
src/runtime/cvm/top/op.cc.i:
	$(MAKE) -f CMakeFiles/cvm_runtime.dir/build.make CMakeFiles/cvm_runtime.dir/src/runtime/cvm/top/op.cc.i
.PHONY : src/runtime/cvm/top/op.cc.i

src/runtime/cvm/top/op.s: src/runtime/cvm/top/op.cc.s

.PHONY : src/runtime/cvm/top/op.s

# target to generate assembly for a file
src/runtime/cvm/top/op.cc.s:
	$(MAKE) -f CMakeFiles/cvm_runtime.dir/build.make CMakeFiles/cvm_runtime.dir/src/runtime/cvm/top/op.cc.s
.PHONY : src/runtime/cvm/top/op.cc.s

src/runtime/cvm/top/tensor/broadcast.o: src/runtime/cvm/top/tensor/broadcast.cc.o

.PHONY : src/runtime/cvm/top/tensor/broadcast.o

# target to build an object file
src/runtime/cvm/top/tensor/broadcast.cc.o:
	$(MAKE) -f CMakeFiles/cvm_runtime.dir/build.make CMakeFiles/cvm_runtime.dir/src/runtime/cvm/top/tensor/broadcast.cc.o
.PHONY : src/runtime/cvm/top/tensor/broadcast.cc.o

src/runtime/cvm/top/tensor/broadcast.i: src/runtime/cvm/top/tensor/broadcast.cc.i

.PHONY : src/runtime/cvm/top/tensor/broadcast.i

# target to preprocess a source file
src/runtime/cvm/top/tensor/broadcast.cc.i:
	$(MAKE) -f CMakeFiles/cvm_runtime.dir/build.make CMakeFiles/cvm_runtime.dir/src/runtime/cvm/top/tensor/broadcast.cc.i
.PHONY : src/runtime/cvm/top/tensor/broadcast.cc.i

src/runtime/cvm/top/tensor/broadcast.s: src/runtime/cvm/top/tensor/broadcast.cc.s

.PHONY : src/runtime/cvm/top/tensor/broadcast.s

# target to generate assembly for a file
src/runtime/cvm/top/tensor/broadcast.cc.s:
	$(MAKE) -f CMakeFiles/cvm_runtime.dir/build.make CMakeFiles/cvm_runtime.dir/src/runtime/cvm/top/tensor/broadcast.cc.s
.PHONY : src/runtime/cvm/top/tensor/broadcast.cc.s

src/runtime/cvm/top/tensor/elemwise.o: src/runtime/cvm/top/tensor/elemwise.cc.o

.PHONY : src/runtime/cvm/top/tensor/elemwise.o

# target to build an object file
src/runtime/cvm/top/tensor/elemwise.cc.o:
	$(MAKE) -f CMakeFiles/cvm_runtime.dir/build.make CMakeFiles/cvm_runtime.dir/src/runtime/cvm/top/tensor/elemwise.cc.o
.PHONY : src/runtime/cvm/top/tensor/elemwise.cc.o

src/runtime/cvm/top/tensor/elemwise.i: src/runtime/cvm/top/tensor/elemwise.cc.i

.PHONY : src/runtime/cvm/top/tensor/elemwise.i

# target to preprocess a source file
src/runtime/cvm/top/tensor/elemwise.cc.i:
	$(MAKE) -f CMakeFiles/cvm_runtime.dir/build.make CMakeFiles/cvm_runtime.dir/src/runtime/cvm/top/tensor/elemwise.cc.i
.PHONY : src/runtime/cvm/top/tensor/elemwise.cc.i

src/runtime/cvm/top/tensor/elemwise.s: src/runtime/cvm/top/tensor/elemwise.cc.s

.PHONY : src/runtime/cvm/top/tensor/elemwise.s

# target to generate assembly for a file
src/runtime/cvm/top/tensor/elemwise.cc.s:
	$(MAKE) -f CMakeFiles/cvm_runtime.dir/build.make CMakeFiles/cvm_runtime.dir/src/runtime/cvm/top/tensor/elemwise.cc.s
.PHONY : src/runtime/cvm/top/tensor/elemwise.cc.s

src/runtime/cvm/top/tensor/matrix_op.o: src/runtime/cvm/top/tensor/matrix_op.cc.o

.PHONY : src/runtime/cvm/top/tensor/matrix_op.o

# target to build an object file
src/runtime/cvm/top/tensor/matrix_op.cc.o:
	$(MAKE) -f CMakeFiles/cvm_runtime.dir/build.make CMakeFiles/cvm_runtime.dir/src/runtime/cvm/top/tensor/matrix_op.cc.o
.PHONY : src/runtime/cvm/top/tensor/matrix_op.cc.o

src/runtime/cvm/top/tensor/matrix_op.i: src/runtime/cvm/top/tensor/matrix_op.cc.i

.PHONY : src/runtime/cvm/top/tensor/matrix_op.i

# target to preprocess a source file
src/runtime/cvm/top/tensor/matrix_op.cc.i:
	$(MAKE) -f CMakeFiles/cvm_runtime.dir/build.make CMakeFiles/cvm_runtime.dir/src/runtime/cvm/top/tensor/matrix_op.cc.i
.PHONY : src/runtime/cvm/top/tensor/matrix_op.cc.i

src/runtime/cvm/top/tensor/matrix_op.s: src/runtime/cvm/top/tensor/matrix_op.cc.s

.PHONY : src/runtime/cvm/top/tensor/matrix_op.s

# target to generate assembly for a file
src/runtime/cvm/top/tensor/matrix_op.cc.s:
	$(MAKE) -f CMakeFiles/cvm_runtime.dir/build.make CMakeFiles/cvm_runtime.dir/src/runtime/cvm/top/tensor/matrix_op.cc.s
.PHONY : src/runtime/cvm/top/tensor/matrix_op.cc.s

src/runtime/cvm/top/tensor/reduce.o: src/runtime/cvm/top/tensor/reduce.cc.o

.PHONY : src/runtime/cvm/top/tensor/reduce.o

# target to build an object file
src/runtime/cvm/top/tensor/reduce.cc.o:
	$(MAKE) -f CMakeFiles/cvm_runtime.dir/build.make CMakeFiles/cvm_runtime.dir/src/runtime/cvm/top/tensor/reduce.cc.o
.PHONY : src/runtime/cvm/top/tensor/reduce.cc.o

src/runtime/cvm/top/tensor/reduce.i: src/runtime/cvm/top/tensor/reduce.cc.i

.PHONY : src/runtime/cvm/top/tensor/reduce.i

# target to preprocess a source file
src/runtime/cvm/top/tensor/reduce.cc.i:
	$(MAKE) -f CMakeFiles/cvm_runtime.dir/build.make CMakeFiles/cvm_runtime.dir/src/runtime/cvm/top/tensor/reduce.cc.i
.PHONY : src/runtime/cvm/top/tensor/reduce.cc.i

src/runtime/cvm/top/tensor/reduce.s: src/runtime/cvm/top/tensor/reduce.cc.s

.PHONY : src/runtime/cvm/top/tensor/reduce.s

# target to generate assembly for a file
src/runtime/cvm/top/tensor/reduce.cc.s:
	$(MAKE) -f CMakeFiles/cvm_runtime.dir/build.make CMakeFiles/cvm_runtime.dir/src/runtime/cvm/top/tensor/reduce.cc.s
.PHONY : src/runtime/cvm/top/tensor/reduce.cc.s

src/runtime/cvm/top/tensor/transform.o: src/runtime/cvm/top/tensor/transform.cc.o

.PHONY : src/runtime/cvm/top/tensor/transform.o

# target to build an object file
src/runtime/cvm/top/tensor/transform.cc.o:
	$(MAKE) -f CMakeFiles/cvm_runtime.dir/build.make CMakeFiles/cvm_runtime.dir/src/runtime/cvm/top/tensor/transform.cc.o
.PHONY : src/runtime/cvm/top/tensor/transform.cc.o

src/runtime/cvm/top/tensor/transform.i: src/runtime/cvm/top/tensor/transform.cc.i

.PHONY : src/runtime/cvm/top/tensor/transform.i

# target to preprocess a source file
src/runtime/cvm/top/tensor/transform.cc.i:
	$(MAKE) -f CMakeFiles/cvm_runtime.dir/build.make CMakeFiles/cvm_runtime.dir/src/runtime/cvm/top/tensor/transform.cc.i
.PHONY : src/runtime/cvm/top/tensor/transform.cc.i

src/runtime/cvm/top/tensor/transform.s: src/runtime/cvm/top/tensor/transform.cc.s

.PHONY : src/runtime/cvm/top/tensor/transform.s

# target to generate assembly for a file
src/runtime/cvm/top/tensor/transform.cc.s:
	$(MAKE) -f CMakeFiles/cvm_runtime.dir/build.make CMakeFiles/cvm_runtime.dir/src/runtime/cvm/top/tensor/transform.cc.s
.PHONY : src/runtime/cvm/top/tensor/transform.cc.s

src/runtime/dso_module.o: src/runtime/dso_module.cc.o

.PHONY : src/runtime/dso_module.o

# target to build an object file
src/runtime/dso_module.cc.o:
	$(MAKE) -f CMakeFiles/cvm_runtime.dir/build.make CMakeFiles/cvm_runtime.dir/src/runtime/dso_module.cc.o
.PHONY : src/runtime/dso_module.cc.o

src/runtime/dso_module.i: src/runtime/dso_module.cc.i

.PHONY : src/runtime/dso_module.i

# target to preprocess a source file
src/runtime/dso_module.cc.i:
	$(MAKE) -f CMakeFiles/cvm_runtime.dir/build.make CMakeFiles/cvm_runtime.dir/src/runtime/dso_module.cc.i
.PHONY : src/runtime/dso_module.cc.i

src/runtime/dso_module.s: src/runtime/dso_module.cc.s

.PHONY : src/runtime/dso_module.s

# target to generate assembly for a file
src/runtime/dso_module.cc.s:
	$(MAKE) -f CMakeFiles/cvm_runtime.dir/build.make CMakeFiles/cvm_runtime.dir/src/runtime/dso_module.cc.s
.PHONY : src/runtime/dso_module.cc.s

src/runtime/file_util.o: src/runtime/file_util.cc.o

.PHONY : src/runtime/file_util.o

# target to build an object file
src/runtime/file_util.cc.o:
	$(MAKE) -f CMakeFiles/cvm_runtime.dir/build.make CMakeFiles/cvm_runtime.dir/src/runtime/file_util.cc.o
.PHONY : src/runtime/file_util.cc.o

src/runtime/file_util.i: src/runtime/file_util.cc.i

.PHONY : src/runtime/file_util.i

# target to preprocess a source file
src/runtime/file_util.cc.i:
	$(MAKE) -f CMakeFiles/cvm_runtime.dir/build.make CMakeFiles/cvm_runtime.dir/src/runtime/file_util.cc.i
.PHONY : src/runtime/file_util.cc.i

src/runtime/file_util.s: src/runtime/file_util.cc.s

.PHONY : src/runtime/file_util.s

# target to generate assembly for a file
src/runtime/file_util.cc.s:
	$(MAKE) -f CMakeFiles/cvm_runtime.dir/build.make CMakeFiles/cvm_runtime.dir/src/runtime/file_util.cc.s
.PHONY : src/runtime/file_util.cc.s

src/runtime/graph/graph_runtime.o: src/runtime/graph/graph_runtime.cc.o

.PHONY : src/runtime/graph/graph_runtime.o

# target to build an object file
src/runtime/graph/graph_runtime.cc.o:
	$(MAKE) -f CMakeFiles/cvm_runtime.dir/build.make CMakeFiles/cvm_runtime.dir/src/runtime/graph/graph_runtime.cc.o
.PHONY : src/runtime/graph/graph_runtime.cc.o

src/runtime/graph/graph_runtime.i: src/runtime/graph/graph_runtime.cc.i

.PHONY : src/runtime/graph/graph_runtime.i

# target to preprocess a source file
src/runtime/graph/graph_runtime.cc.i:
	$(MAKE) -f CMakeFiles/cvm_runtime.dir/build.make CMakeFiles/cvm_runtime.dir/src/runtime/graph/graph_runtime.cc.i
.PHONY : src/runtime/graph/graph_runtime.cc.i

src/runtime/graph/graph_runtime.s: src/runtime/graph/graph_runtime.cc.s

.PHONY : src/runtime/graph/graph_runtime.s

# target to generate assembly for a file
src/runtime/graph/graph_runtime.cc.s:
	$(MAKE) -f CMakeFiles/cvm_runtime.dir/build.make CMakeFiles/cvm_runtime.dir/src/runtime/graph/graph_runtime.cc.s
.PHONY : src/runtime/graph/graph_runtime.cc.s

src/runtime/module.o: src/runtime/module.cc.o

.PHONY : src/runtime/module.o

# target to build an object file
src/runtime/module.cc.o:
	$(MAKE) -f CMakeFiles/cvm_runtime.dir/build.make CMakeFiles/cvm_runtime.dir/src/runtime/module.cc.o
.PHONY : src/runtime/module.cc.o

src/runtime/module.i: src/runtime/module.cc.i

.PHONY : src/runtime/module.i

# target to preprocess a source file
src/runtime/module.cc.i:
	$(MAKE) -f CMakeFiles/cvm_runtime.dir/build.make CMakeFiles/cvm_runtime.dir/src/runtime/module.cc.i
.PHONY : src/runtime/module.cc.i

src/runtime/module.s: src/runtime/module.cc.s

.PHONY : src/runtime/module.s

# target to generate assembly for a file
src/runtime/module.cc.s:
	$(MAKE) -f CMakeFiles/cvm_runtime.dir/build.make CMakeFiles/cvm_runtime.dir/src/runtime/module.cc.s
.PHONY : src/runtime/module.cc.s

src/runtime/module_util.o: src/runtime/module_util.cc.o

.PHONY : src/runtime/module_util.o

# target to build an object file
src/runtime/module_util.cc.o:
	$(MAKE) -f CMakeFiles/cvm_runtime.dir/build.make CMakeFiles/cvm_runtime.dir/src/runtime/module_util.cc.o
.PHONY : src/runtime/module_util.cc.o

src/runtime/module_util.i: src/runtime/module_util.cc.i

.PHONY : src/runtime/module_util.i

# target to preprocess a source file
src/runtime/module_util.cc.i:
	$(MAKE) -f CMakeFiles/cvm_runtime.dir/build.make CMakeFiles/cvm_runtime.dir/src/runtime/module_util.cc.i
.PHONY : src/runtime/module_util.cc.i

src/runtime/module_util.s: src/runtime/module_util.cc.s

.PHONY : src/runtime/module_util.s

# target to generate assembly for a file
src/runtime/module_util.cc.s:
	$(MAKE) -f CMakeFiles/cvm_runtime.dir/build.make CMakeFiles/cvm_runtime.dir/src/runtime/module_util.cc.s
.PHONY : src/runtime/module_util.cc.s

src/runtime/ndarray.o: src/runtime/ndarray.cc.o

.PHONY : src/runtime/ndarray.o

# target to build an object file
src/runtime/ndarray.cc.o:
	$(MAKE) -f CMakeFiles/cvm_runtime.dir/build.make CMakeFiles/cvm_runtime.dir/src/runtime/ndarray.cc.o
.PHONY : src/runtime/ndarray.cc.o

src/runtime/ndarray.i: src/runtime/ndarray.cc.i

.PHONY : src/runtime/ndarray.i

# target to preprocess a source file
src/runtime/ndarray.cc.i:
	$(MAKE) -f CMakeFiles/cvm_runtime.dir/build.make CMakeFiles/cvm_runtime.dir/src/runtime/ndarray.cc.i
.PHONY : src/runtime/ndarray.cc.i

src/runtime/ndarray.s: src/runtime/ndarray.cc.s

.PHONY : src/runtime/ndarray.s

# target to generate assembly for a file
src/runtime/ndarray.cc.s:
	$(MAKE) -f CMakeFiles/cvm_runtime.dir/build.make CMakeFiles/cvm_runtime.dir/src/runtime/ndarray.cc.s
.PHONY : src/runtime/ndarray.cc.s

src/runtime/registry.o: src/runtime/registry.cc.o

.PHONY : src/runtime/registry.o

# target to build an object file
src/runtime/registry.cc.o:
	$(MAKE) -f CMakeFiles/cvm_runtime.dir/build.make CMakeFiles/cvm_runtime.dir/src/runtime/registry.cc.o
.PHONY : src/runtime/registry.cc.o

src/runtime/registry.i: src/runtime/registry.cc.i

.PHONY : src/runtime/registry.i

# target to preprocess a source file
src/runtime/registry.cc.i:
	$(MAKE) -f CMakeFiles/cvm_runtime.dir/build.make CMakeFiles/cvm_runtime.dir/src/runtime/registry.cc.i
.PHONY : src/runtime/registry.cc.i

src/runtime/registry.s: src/runtime/registry.cc.s

.PHONY : src/runtime/registry.s

# target to generate assembly for a file
src/runtime/registry.cc.s:
	$(MAKE) -f CMakeFiles/cvm_runtime.dir/build.make CMakeFiles/cvm_runtime.dir/src/runtime/registry.cc.s
.PHONY : src/runtime/registry.cc.s

src/runtime/rpc/rpc_device_api.o: src/runtime/rpc/rpc_device_api.cc.o

.PHONY : src/runtime/rpc/rpc_device_api.o

# target to build an object file
src/runtime/rpc/rpc_device_api.cc.o:
	$(MAKE) -f CMakeFiles/cvm_runtime.dir/build.make CMakeFiles/cvm_runtime.dir/src/runtime/rpc/rpc_device_api.cc.o
.PHONY : src/runtime/rpc/rpc_device_api.cc.o

src/runtime/rpc/rpc_device_api.i: src/runtime/rpc/rpc_device_api.cc.i

.PHONY : src/runtime/rpc/rpc_device_api.i

# target to preprocess a source file
src/runtime/rpc/rpc_device_api.cc.i:
	$(MAKE) -f CMakeFiles/cvm_runtime.dir/build.make CMakeFiles/cvm_runtime.dir/src/runtime/rpc/rpc_device_api.cc.i
.PHONY : src/runtime/rpc/rpc_device_api.cc.i

src/runtime/rpc/rpc_device_api.s: src/runtime/rpc/rpc_device_api.cc.s

.PHONY : src/runtime/rpc/rpc_device_api.s

# target to generate assembly for a file
src/runtime/rpc/rpc_device_api.cc.s:
	$(MAKE) -f CMakeFiles/cvm_runtime.dir/build.make CMakeFiles/cvm_runtime.dir/src/runtime/rpc/rpc_device_api.cc.s
.PHONY : src/runtime/rpc/rpc_device_api.cc.s

src/runtime/rpc/rpc_event_impl.o: src/runtime/rpc/rpc_event_impl.cc.o

.PHONY : src/runtime/rpc/rpc_event_impl.o

# target to build an object file
src/runtime/rpc/rpc_event_impl.cc.o:
	$(MAKE) -f CMakeFiles/cvm_runtime.dir/build.make CMakeFiles/cvm_runtime.dir/src/runtime/rpc/rpc_event_impl.cc.o
.PHONY : src/runtime/rpc/rpc_event_impl.cc.o

src/runtime/rpc/rpc_event_impl.i: src/runtime/rpc/rpc_event_impl.cc.i

.PHONY : src/runtime/rpc/rpc_event_impl.i

# target to preprocess a source file
src/runtime/rpc/rpc_event_impl.cc.i:
	$(MAKE) -f CMakeFiles/cvm_runtime.dir/build.make CMakeFiles/cvm_runtime.dir/src/runtime/rpc/rpc_event_impl.cc.i
.PHONY : src/runtime/rpc/rpc_event_impl.cc.i

src/runtime/rpc/rpc_event_impl.s: src/runtime/rpc/rpc_event_impl.cc.s

.PHONY : src/runtime/rpc/rpc_event_impl.s

# target to generate assembly for a file
src/runtime/rpc/rpc_event_impl.cc.s:
	$(MAKE) -f CMakeFiles/cvm_runtime.dir/build.make CMakeFiles/cvm_runtime.dir/src/runtime/rpc/rpc_event_impl.cc.s
.PHONY : src/runtime/rpc/rpc_event_impl.cc.s

src/runtime/rpc/rpc_module.o: src/runtime/rpc/rpc_module.cc.o

.PHONY : src/runtime/rpc/rpc_module.o

# target to build an object file
src/runtime/rpc/rpc_module.cc.o:
	$(MAKE) -f CMakeFiles/cvm_runtime.dir/build.make CMakeFiles/cvm_runtime.dir/src/runtime/rpc/rpc_module.cc.o
.PHONY : src/runtime/rpc/rpc_module.cc.o

src/runtime/rpc/rpc_module.i: src/runtime/rpc/rpc_module.cc.i

.PHONY : src/runtime/rpc/rpc_module.i

# target to preprocess a source file
src/runtime/rpc/rpc_module.cc.i:
	$(MAKE) -f CMakeFiles/cvm_runtime.dir/build.make CMakeFiles/cvm_runtime.dir/src/runtime/rpc/rpc_module.cc.i
.PHONY : src/runtime/rpc/rpc_module.cc.i

src/runtime/rpc/rpc_module.s: src/runtime/rpc/rpc_module.cc.s

.PHONY : src/runtime/rpc/rpc_module.s

# target to generate assembly for a file
src/runtime/rpc/rpc_module.cc.s:
	$(MAKE) -f CMakeFiles/cvm_runtime.dir/build.make CMakeFiles/cvm_runtime.dir/src/runtime/rpc/rpc_module.cc.s
.PHONY : src/runtime/rpc/rpc_module.cc.s

src/runtime/rpc/rpc_server_env.o: src/runtime/rpc/rpc_server_env.cc.o

.PHONY : src/runtime/rpc/rpc_server_env.o

# target to build an object file
src/runtime/rpc/rpc_server_env.cc.o:
	$(MAKE) -f CMakeFiles/cvm_runtime.dir/build.make CMakeFiles/cvm_runtime.dir/src/runtime/rpc/rpc_server_env.cc.o
.PHONY : src/runtime/rpc/rpc_server_env.cc.o

src/runtime/rpc/rpc_server_env.i: src/runtime/rpc/rpc_server_env.cc.i

.PHONY : src/runtime/rpc/rpc_server_env.i

# target to preprocess a source file
src/runtime/rpc/rpc_server_env.cc.i:
	$(MAKE) -f CMakeFiles/cvm_runtime.dir/build.make CMakeFiles/cvm_runtime.dir/src/runtime/rpc/rpc_server_env.cc.i
.PHONY : src/runtime/rpc/rpc_server_env.cc.i

src/runtime/rpc/rpc_server_env.s: src/runtime/rpc/rpc_server_env.cc.s

.PHONY : src/runtime/rpc/rpc_server_env.s

# target to generate assembly for a file
src/runtime/rpc/rpc_server_env.cc.s:
	$(MAKE) -f CMakeFiles/cvm_runtime.dir/build.make CMakeFiles/cvm_runtime.dir/src/runtime/rpc/rpc_server_env.cc.s
.PHONY : src/runtime/rpc/rpc_server_env.cc.s

src/runtime/rpc/rpc_session.o: src/runtime/rpc/rpc_session.cc.o

.PHONY : src/runtime/rpc/rpc_session.o

# target to build an object file
src/runtime/rpc/rpc_session.cc.o:
	$(MAKE) -f CMakeFiles/cvm_runtime.dir/build.make CMakeFiles/cvm_runtime.dir/src/runtime/rpc/rpc_session.cc.o
.PHONY : src/runtime/rpc/rpc_session.cc.o

src/runtime/rpc/rpc_session.i: src/runtime/rpc/rpc_session.cc.i

.PHONY : src/runtime/rpc/rpc_session.i

# target to preprocess a source file
src/runtime/rpc/rpc_session.cc.i:
	$(MAKE) -f CMakeFiles/cvm_runtime.dir/build.make CMakeFiles/cvm_runtime.dir/src/runtime/rpc/rpc_session.cc.i
.PHONY : src/runtime/rpc/rpc_session.cc.i

src/runtime/rpc/rpc_session.s: src/runtime/rpc/rpc_session.cc.s

.PHONY : src/runtime/rpc/rpc_session.s

# target to generate assembly for a file
src/runtime/rpc/rpc_session.cc.s:
	$(MAKE) -f CMakeFiles/cvm_runtime.dir/build.make CMakeFiles/cvm_runtime.dir/src/runtime/rpc/rpc_session.cc.s
.PHONY : src/runtime/rpc/rpc_session.cc.s

src/runtime/rpc/rpc_socket_impl.o: src/runtime/rpc/rpc_socket_impl.cc.o

.PHONY : src/runtime/rpc/rpc_socket_impl.o

# target to build an object file
src/runtime/rpc/rpc_socket_impl.cc.o:
	$(MAKE) -f CMakeFiles/cvm_runtime.dir/build.make CMakeFiles/cvm_runtime.dir/src/runtime/rpc/rpc_socket_impl.cc.o
.PHONY : src/runtime/rpc/rpc_socket_impl.cc.o

src/runtime/rpc/rpc_socket_impl.i: src/runtime/rpc/rpc_socket_impl.cc.i

.PHONY : src/runtime/rpc/rpc_socket_impl.i

# target to preprocess a source file
src/runtime/rpc/rpc_socket_impl.cc.i:
	$(MAKE) -f CMakeFiles/cvm_runtime.dir/build.make CMakeFiles/cvm_runtime.dir/src/runtime/rpc/rpc_socket_impl.cc.i
.PHONY : src/runtime/rpc/rpc_socket_impl.cc.i

src/runtime/rpc/rpc_socket_impl.s: src/runtime/rpc/rpc_socket_impl.cc.s

.PHONY : src/runtime/rpc/rpc_socket_impl.s

# target to generate assembly for a file
src/runtime/rpc/rpc_socket_impl.cc.s:
	$(MAKE) -f CMakeFiles/cvm_runtime.dir/build.make CMakeFiles/cvm_runtime.dir/src/runtime/rpc/rpc_socket_impl.cc.s
.PHONY : src/runtime/rpc/rpc_socket_impl.cc.s

src/runtime/system_lib_module.o: src/runtime/system_lib_module.cc.o

.PHONY : src/runtime/system_lib_module.o

# target to build an object file
src/runtime/system_lib_module.cc.o:
	$(MAKE) -f CMakeFiles/cvm_runtime.dir/build.make CMakeFiles/cvm_runtime.dir/src/runtime/system_lib_module.cc.o
.PHONY : src/runtime/system_lib_module.cc.o

src/runtime/system_lib_module.i: src/runtime/system_lib_module.cc.i

.PHONY : src/runtime/system_lib_module.i

# target to preprocess a source file
src/runtime/system_lib_module.cc.i:
	$(MAKE) -f CMakeFiles/cvm_runtime.dir/build.make CMakeFiles/cvm_runtime.dir/src/runtime/system_lib_module.cc.i
.PHONY : src/runtime/system_lib_module.cc.i

src/runtime/system_lib_module.s: src/runtime/system_lib_module.cc.s

.PHONY : src/runtime/system_lib_module.s

# target to generate assembly for a file
src/runtime/system_lib_module.cc.s:
	$(MAKE) -f CMakeFiles/cvm_runtime.dir/build.make CMakeFiles/cvm_runtime.dir/src/runtime/system_lib_module.cc.s
.PHONY : src/runtime/system_lib_module.cc.s

src/runtime/thread_pool.o: src/runtime/thread_pool.cc.o

.PHONY : src/runtime/thread_pool.o

# target to build an object file
src/runtime/thread_pool.cc.o:
	$(MAKE) -f CMakeFiles/cvm_runtime.dir/build.make CMakeFiles/cvm_runtime.dir/src/runtime/thread_pool.cc.o
.PHONY : src/runtime/thread_pool.cc.o

src/runtime/thread_pool.i: src/runtime/thread_pool.cc.i

.PHONY : src/runtime/thread_pool.i

# target to preprocess a source file
src/runtime/thread_pool.cc.i:
	$(MAKE) -f CMakeFiles/cvm_runtime.dir/build.make CMakeFiles/cvm_runtime.dir/src/runtime/thread_pool.cc.i
.PHONY : src/runtime/thread_pool.cc.i

src/runtime/thread_pool.s: src/runtime/thread_pool.cc.s

.PHONY : src/runtime/thread_pool.s

# target to generate assembly for a file
src/runtime/thread_pool.cc.s:
	$(MAKE) -f CMakeFiles/cvm_runtime.dir/build.make CMakeFiles/cvm_runtime.dir/src/runtime/thread_pool.cc.s
.PHONY : src/runtime/thread_pool.cc.s

src/runtime/threading_backend.o: src/runtime/threading_backend.cc.o

.PHONY : src/runtime/threading_backend.o

# target to build an object file
src/runtime/threading_backend.cc.o:
	$(MAKE) -f CMakeFiles/cvm_runtime.dir/build.make CMakeFiles/cvm_runtime.dir/src/runtime/threading_backend.cc.o
.PHONY : src/runtime/threading_backend.cc.o

src/runtime/threading_backend.i: src/runtime/threading_backend.cc.i

.PHONY : src/runtime/threading_backend.i

# target to preprocess a source file
src/runtime/threading_backend.cc.i:
	$(MAKE) -f CMakeFiles/cvm_runtime.dir/build.make CMakeFiles/cvm_runtime.dir/src/runtime/threading_backend.cc.i
.PHONY : src/runtime/threading_backend.cc.i

src/runtime/threading_backend.s: src/runtime/threading_backend.cc.s

.PHONY : src/runtime/threading_backend.s

# target to generate assembly for a file
src/runtime/threading_backend.cc.s:
	$(MAKE) -f CMakeFiles/cvm_runtime.dir/build.make CMakeFiles/cvm_runtime.dir/src/runtime/threading_backend.cc.s
.PHONY : src/runtime/threading_backend.cc.s

src/runtime/workspace_pool.o: src/runtime/workspace_pool.cc.o

.PHONY : src/runtime/workspace_pool.o

# target to build an object file
src/runtime/workspace_pool.cc.o:
	$(MAKE) -f CMakeFiles/cvm_runtime.dir/build.make CMakeFiles/cvm_runtime.dir/src/runtime/workspace_pool.cc.o
.PHONY : src/runtime/workspace_pool.cc.o

src/runtime/workspace_pool.i: src/runtime/workspace_pool.cc.i

.PHONY : src/runtime/workspace_pool.i

# target to preprocess a source file
src/runtime/workspace_pool.cc.i:
	$(MAKE) -f CMakeFiles/cvm_runtime.dir/build.make CMakeFiles/cvm_runtime.dir/src/runtime/workspace_pool.cc.i
.PHONY : src/runtime/workspace_pool.cc.i

src/runtime/workspace_pool.s: src/runtime/workspace_pool.cc.s

.PHONY : src/runtime/workspace_pool.s

# target to generate assembly for a file
src/runtime/workspace_pool.cc.s:
	$(MAKE) -f CMakeFiles/cvm_runtime.dir/build.make CMakeFiles/cvm_runtime.dir/src/runtime/workspace_pool.cc.s
.PHONY : src/runtime/workspace_pool.cc.s

# Help Target
help:
	@echo "The following are some of the valid targets for this Makefile:"
	@echo "... all (the default if no target is provided)"
	@echo "... clean"
	@echo "... depend"
	@echo "... install/strip"
	@echo "... install/local"
	@echo "... install"
	@echo "... list_install_components"
	@echo "... cvm_runtime"
	@echo "... runtime"
	@echo "... rebuild_cache"
	@echo "... edit_cache"
	@echo "... src/runtime/c_dsl_api.o"
	@echo "... src/runtime/c_dsl_api.i"
	@echo "... src/runtime/c_dsl_api.s"
	@echo "... src/runtime/c_runtime_api.o"
	@echo "... src/runtime/c_runtime_api.i"
	@echo "... src/runtime/c_runtime_api.s"
	@echo "... src/runtime/cpu_device_api.o"
	@echo "... src/runtime/cpu_device_api.i"
	@echo "... src/runtime/cpu_device_api.s"
	@echo "... src/runtime/cuda/cuda_device_api.o"
	@echo "... src/runtime/cuda/cuda_device_api.i"
	@echo "... src/runtime/cuda/cuda_device_api.s"
	@echo "... src/runtime/cuda/cuda_module.o"
	@echo "... src/runtime/cuda/cuda_module.i"
	@echo "... src/runtime/cuda/cuda_module.s"
	@echo "... src/runtime/cvm/graph_runtime.o"
	@echo "... src/runtime/cvm/graph_runtime.i"
	@echo "... src/runtime/cvm/graph_runtime.s"
	@echo "... src/runtime/cvm/infer_attr.o"
	@echo "... src/runtime/cvm/infer_attr.i"
	@echo "... src/runtime/cvm/infer_attr.s"
	@echo "... src/runtime/cvm/ops.o"
	@echo "... src/runtime/cvm/ops.i"
	@echo "... src/runtime/cvm/ops.s"
	@echo "... src/runtime/cvm/top/nn/convolution.o"
	@echo "... src/runtime/cvm/top/nn/convolution.i"
	@echo "... src/runtime/cvm/top/nn/convolution.s"
	@echo "... src/runtime/cvm/top/nn/nn.o"
	@echo "... src/runtime/cvm/top/nn/nn.i"
	@echo "... src/runtime/cvm/top/nn/nn.s"
	@echo "... src/runtime/cvm/top/nn/pooling.o"
	@echo "... src/runtime/cvm/top/nn/pooling.i"
	@echo "... src/runtime/cvm/top/nn/pooling.s"
	@echo "... src/runtime/cvm/top/node.o"
	@echo "... src/runtime/cvm/top/node.i"
	@echo "... src/runtime/cvm/top/node.s"
	@echo "... src/runtime/cvm/top/op.o"
	@echo "... src/runtime/cvm/top/op.i"
	@echo "... src/runtime/cvm/top/op.s"
	@echo "... src/runtime/cvm/top/tensor/broadcast.o"
	@echo "... src/runtime/cvm/top/tensor/broadcast.i"
	@echo "... src/runtime/cvm/top/tensor/broadcast.s"
	@echo "... src/runtime/cvm/top/tensor/elemwise.o"
	@echo "... src/runtime/cvm/top/tensor/elemwise.i"
	@echo "... src/runtime/cvm/top/tensor/elemwise.s"
	@echo "... src/runtime/cvm/top/tensor/matrix_op.o"
	@echo "... src/runtime/cvm/top/tensor/matrix_op.i"
	@echo "... src/runtime/cvm/top/tensor/matrix_op.s"
	@echo "... src/runtime/cvm/top/tensor/reduce.o"
	@echo "... src/runtime/cvm/top/tensor/reduce.i"
	@echo "... src/runtime/cvm/top/tensor/reduce.s"
	@echo "... src/runtime/cvm/top/tensor/transform.o"
	@echo "... src/runtime/cvm/top/tensor/transform.i"
	@echo "... src/runtime/cvm/top/tensor/transform.s"
	@echo "... src/runtime/dso_module.o"
	@echo "... src/runtime/dso_module.i"
	@echo "... src/runtime/dso_module.s"
	@echo "... src/runtime/file_util.o"
	@echo "... src/runtime/file_util.i"
	@echo "... src/runtime/file_util.s"
	@echo "... src/runtime/graph/graph_runtime.o"
	@echo "... src/runtime/graph/graph_runtime.i"
	@echo "... src/runtime/graph/graph_runtime.s"
	@echo "... src/runtime/module.o"
	@echo "... src/runtime/module.i"
	@echo "... src/runtime/module.s"
	@echo "... src/runtime/module_util.o"
	@echo "... src/runtime/module_util.i"
	@echo "... src/runtime/module_util.s"
	@echo "... src/runtime/ndarray.o"
	@echo "... src/runtime/ndarray.i"
	@echo "... src/runtime/ndarray.s"
	@echo "... src/runtime/registry.o"
	@echo "... src/runtime/registry.i"
	@echo "... src/runtime/registry.s"
	@echo "... src/runtime/rpc/rpc_device_api.o"
	@echo "... src/runtime/rpc/rpc_device_api.i"
	@echo "... src/runtime/rpc/rpc_device_api.s"
	@echo "... src/runtime/rpc/rpc_event_impl.o"
	@echo "... src/runtime/rpc/rpc_event_impl.i"
	@echo "... src/runtime/rpc/rpc_event_impl.s"
	@echo "... src/runtime/rpc/rpc_module.o"
	@echo "... src/runtime/rpc/rpc_module.i"
	@echo "... src/runtime/rpc/rpc_module.s"
	@echo "... src/runtime/rpc/rpc_server_env.o"
	@echo "... src/runtime/rpc/rpc_server_env.i"
	@echo "... src/runtime/rpc/rpc_server_env.s"
	@echo "... src/runtime/rpc/rpc_session.o"
	@echo "... src/runtime/rpc/rpc_session.i"
	@echo "... src/runtime/rpc/rpc_session.s"
	@echo "... src/runtime/rpc/rpc_socket_impl.o"
	@echo "... src/runtime/rpc/rpc_socket_impl.i"
	@echo "... src/runtime/rpc/rpc_socket_impl.s"
	@echo "... src/runtime/system_lib_module.o"
	@echo "... src/runtime/system_lib_module.i"
	@echo "... src/runtime/system_lib_module.s"
	@echo "... src/runtime/thread_pool.o"
	@echo "... src/runtime/thread_pool.i"
	@echo "... src/runtime/thread_pool.s"
	@echo "... src/runtime/threading_backend.o"
	@echo "... src/runtime/threading_backend.i"
	@echo "... src/runtime/threading_backend.s"
	@echo "... src/runtime/workspace_pool.o"
	@echo "... src/runtime/workspace_pool.i"
	@echo "... src/runtime/workspace_pool.s"
.PHONY : help



#=============================================================================
# Special targets to cleanup operation of make.

# Special rule to run CMake to check the build system integrity.
# No rule that depends on this can have commands that come from listfiles
# because they might be regenerated.
cmake_check_build_system:
	$(CMAKE_COMMAND) -S$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR) --check-build-system CMakeFiles/Makefile.cmake 0
.PHONY : cmake_check_build_system

