from yacs.config import CfgNode as CN
from . import conf
from mrt import mrt_entry as mentry

MRT_CFG = CN()

MRT_CFG.COMMON = CN()
MRT_CFG.COMMON.MODEL_DIR = conf.MRT_MODEL_ROOT
MRT_CFG.COMMON.MODEL_NAME = conf.MRT_MODEL_ROOT
MRT_CFG.COMMON.VERBOSITY = "debug"

MRT_CFG.PREPARE = CN()
MRT_CFG.PREPARE.DEVICE_TYPE = "cpu"
MRT_CFG.PREPARE.DEVICE_IDS = [0]
MRT_CFG.PREPARE.INPUT_SHAPE = [-1, 3, 224, 224]
MRT_CFG.PREPARE.SPLIT_KEYS = ""

MRT_CFG.CALIBRATE = CN()
MRT_CFG.CALIBRATE.BATCH = mentry.default_batch
MRT_CFG.CALIBRATE.NUM = 1
MRT_CFG.CALIBRATE.LAMBD = None
MRT_CFG.CALIBRATE.DATASET_NAME = "imagenet"
MRT_CFG.CALIBRATE.DATASET_DIR = conf.MRT_DATASET_ROOT
MRT_CFG.CALIBRATE.DEVICE_TYPE = "cpu"
MRT_CFG.CALIBRATE.DEVICE_IDS = [0]

MRT_CFG.QUANTIZE = CN()
MRT_CFG.QUANTIZE.RESTORE_NAMES = []
MRT_CFG.QUANTIZE.INPUT_PRECISION = None
MRT_CFG.QUANTIZE.OUTPUT_PRECISION = None
MRT_CFG.QUANTIZE.DEVICE_TYPE = "cpu"
MRT_CFG.QUANTIZE.DEVICE_IDS = [0]
MRT_CFG.QUANTIZE.SOFTMAX_LAMBD = None
MRT_CFG.QUANTIZE.SHIFT_BITS = None
MRT_CFG.QUANTIZE.THRESHOLDS = None
MRT_CFG.QUANTIZE.ATTRIBUTE_DEPS = None
MRT_CFG.QUANTIZE.OSCALE_MAPS = None

MRT_CFG.EVALUATE = CN()
MRT_CFG.EVALUATE.BATCH = mentry.default_batch
MRT_CFG.EVALUATE.DEVICE_TYPE = "cpu"
MRT_CFG.EVALUATE.DEVICE_IDS = [0]
MRT_CFG.EVALUATE.ITER_NUM = 10

MRT_CFG.COMPILE = CN()
MRT_CFG.COMPILE.DUMP_DIR = "/data1/tmp"
MRT_CFG.COMPILE.DEVICE_TYPE = "cpu"
MRT_CFG.COMPILE.DEVICE_IDS = [0]

def get_cfg_defaults():
    """Get a yacs CfgNode object with default values for mrt."""
    # Return a clone so that the defaults will not be altered
    # This is for the "local variable" use pattern
    return MRT_CFG.clone()
